# Generated by Django 2.1.3 on 2018-11-19 02:48

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20181118_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 19, 2, 48, 12, 777361, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 19, 2, 48, 12, 824161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='weightentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
