# Generated by Django 2.1.3 on 2018-12-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20181201_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisracket',
            name='variation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
