# Generated by Django 2.1.3 on 2018-12-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_tennisracket_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisstringjob',
            name='racket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.TennisRacket'),
        ),
    ]
