# Generated by Django 2.1.3 on 2018-12-02 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_tennisstringjob_racket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('journalentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.JournalEntry')),
                ('weight_lb', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight in lb')),
            ],
            bases=('journal.journalentry',),
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_date'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='tennisracket',
            options={'ordering': ['make', 'model', 'variation'], 'verbose_name': 'Tennis Racket', 'verbose_name_plural': 'Tennis Rackets'},
        ),
        migrations.AlterModelOptions(
            name='tennisstring',
            options={'ordering': ['make', 'model', 'variation', 'gauge'], 'verbose_name': 'Tennis String', 'verbose_name_plural': 'Tennis Strings'},
        ),
        migrations.AlterModelOptions(
            name='tennisstringjob',
            options={'ordering': ['-created_date'], 'verbose_name': 'Tennis Stringing Job', 'verbose_name_plural': 'Tennis Stringing Jobs'},
        ),
        migrations.AlterModelOptions(
            name='weightentry',
            options={'ordering': ['-created_date'], 'verbose_name': 'Weight Entry', 'verbose_name_plural': 'Weight Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('wl', 'Weight log'), ('rl', 'Reading log'), ('hl', 'Habit log'), ('bw', 'Bodyweight workout'), ('sw', 'Swim workout'), ('ts', 'Tennis string job'), ('tp', 'Tennis machine practice'), ('th', 'Tennis hitting session'), ('tm', 'Tennis match'), ('bl', 'Breakfast log'), ('ll', 'Lunch log'), ('dl', 'Dinner log'), ('sl', 'Snack log')], help_text='Journal entry type', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='balance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='head_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Head Size'),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='max_tension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Tension'),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='min_tension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Tension'),
        ),
        migrations.AlterField(
            model_name='tennisracket',
            name='variation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='tennisstring',
            name='variation',
            field=models.CharField(blank=True, default='', help_text='Enter string model variation or generation.', max_length=100),
        ),
    ]
