# Generated by Django 2.1.3 on 2018-12-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20181202_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('wl', 'Weight log'), ('rl', 'Reading log'), ('hl', 'Habit log'), ('dr', 'Daily review'), ('wr', 'Weekly review'), ('bw', 'Bodyweight workout'), ('sw', 'Swim workout'), ('ts', 'Tennis string job'), ('tp', 'Tennis machine practice'), ('th', 'Tennis hitting session'), ('tm', 'Tennis match'), ('bl', 'Breakfast log'), ('ll', 'Lunch log'), ('dl', 'Dinner log'), ('sl', 'Snack log')], help_text='Journal entry type', max_length=3, null=True),
        ),
    ]
