# Generated by Django 2.1.3 on 2018-12-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20181203_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('wiki_page', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter book title.', max_length=250, verbose_name='Title')),
                ('total_pages', models.IntegerField(blank=True, help_text='Enter total number of pages.', null=True, verbose_name='Total pages')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000, verbose_name='Brief Summary')),
                ('review_url', models.URLField(blank=True, help_text='Enter book review web page.', null=True, verbose_name='Online review page')),
                ('library_url', models.URLField(blank=True, help_text='Enter library web page.', null=True, verbose_name='Library page')),
                ('isbn', models.CharField(help_text='13 Character <a href="https://en.wikipedia.org/wiki/International_Standard_Book_Number">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('completed', models.BooleanField(default=False, help_text='Have you finished reading the book?')),
                ('authors', models.ManyToManyField(help_text='Select book authors.', to='journal.Author', verbose_name='Authors')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('journalentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.JournalEntry')),
                ('page', models.IntegerField()),
                ('weight_lb', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight in lb')),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Book')),
            ],
            bases=('journal.journalentry',),
        ),
        migrations.AlterModelOptions(
            name='tennisracket',
            options={'ordering': ('make', 'model', 'variation'), 'verbose_name': 'Tennis Racket', 'verbose_name_plural': 'Tennis Rackets'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('wl', 'Weight log'), ('rl', 'Reading log'), ('hl', 'Habit log'), ('dr', 'Daily review'), ('wr', 'Weekly review'), ('bw', 'Body-weight workout'), ('sw', 'Swim workout'), ('ts', 'Tennis string job'), ('tp', 'Tennis machine practice'), ('th', 'Tennis hitting session'), ('tm', 'Tennis match'), ('bl', 'Breakfast log'), ('ll', 'Lunch log'), ('dl', 'Dinner log'), ('sl', 'Snack log')], help_text='Journal entry type', max_length=3, null=True),
        ),
    ]
