# Generated by Django 2.1.3 on 2018-12-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20181203_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='13 Character <a href="https://en.wikipedia.org/wiki/International_Standard_Book_Number">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000, null=True, verbose_name='Brief Summary'),
        ),
    ]
