# Generated by Django 2.1.3 on 2018-12-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20181203_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglog',
            name='weight_lb',
        ),
    ]
