# Generated by Django 2.1.3 on 2018-12-11 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0012_remove_readinglog_weight_lb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ('-status_date',),
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='readinglog',
            name='completed',
        ),
        migrations.AddField(
            model_name='bookstatus',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Book'),
        ),
        migrations.AddField(
            model_name='bookstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
