# Generated by Django 2.1.3 on 2018-12-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20181211_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatusRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'ordering': ('-status_date',), 'verbose_name': 'Book Status', 'verbose_name_plural': 'Books Statuses'},
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.BookStatusRef'),
        ),
    ]
