# Generated by Django 2.1.3 on 2018-12-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_bookstatusref_logical_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatusref',
            options={'ordering': ('logical_order',)},
        ),
    ]
