# Generated by Django 2.1.3 on 2018-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20181211_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatusref',
            name='logical_order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, unique=True),
            preserve_default=False,
        ),
    ]
