# Generated by Django 2.1.3 on 2018-12-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_auto_20181211_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='Select book author.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Author', verbose_name='Author'),
        ),
    ]
