# Generated by Django 2.2.6 on 2019-11-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_auto_20181211_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatus',
            options={'ordering': ('-status_date',), 'verbose_name': 'Book Status', 'verbose_name_plural': 'Book Statuses'},
        ),
        migrations.AddField(
            model_name='book',
            name='is_ebook',
            field=models.BooleanField(blank=True, default=0, help_text='Is this an e-book?'),
        ),
    ]
