# Generated by Django 2.2.6 on 2019-11-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_auto_20191103_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Last Name'),
        ),
    ]
